### ISSUE TITLE
Curious behaviors I cannot figure out!

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [sekureco42/esphome-hub75#1]
I have 5 rgb panel clocks that I made using the Adafruit hardware and circuit python. I love them and they help me not be late to meetings at home! But circuit python is not stable....they crash a lot.

I wanted to make a esphome version of them so I bought some of the trinity esp32 boards to try to mimic my clock. I have made a basic clock but have not been able to mimic all the features of my current clock. I am not overly concerned because I know I can mimic scrolling text with pages and lambdas.

however, I cannot get your code to show any color other than red. Which is really odd. I use all your examples and every time the color is 100% red. I cannot even control the brightness (though it does fade in on reboot).

Any idea on why this might be the case? The are the ICN2037BP chip type, which is supposedly comparable with FM6124.

Also I upgraded the code to the latest version of the library to see if that helped and managed to get 2x the frame rate! I just had to add some logging to your code that the compiler demanded.

I am assuming you see other colors than red...hahaha!

**Comment by sekureco42** [comment]
This component is using the base library https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA to support HUB75 panels. Unfortunately many different variants of HUB75 panels exist (chips used on the panel). So please check the mentioned project to get support for your particular panel.

Regarding your point that a newer version of the base library will get a higher framerate is a valid point - unfortunately as you also described modifications on the source library are necessary. If you could supply your additions to the logging I'm able to upgrade the base library too.

**Comment by disruptivepatternmaterial** [comment]
So I am digging into the library and seeing there are some hacks or quirks people have created for the nuances of panels. It seems to have something to do with the scan rates 1/32 vs 1/8 and such.

Perhaps I just need to expose that up to ESPHOME if I can get it right. I'm starting with hard coding it in the demo code from that project and then will see if I can abstract it upward into your code.  If I can, I'll make a PR for that.

I'll make a PR when I get home for the library update - the frame rate when from 18-20 to pushing 60 at times!!

Thanks for doing this, super cool...I really want to be able to send alerts and updates from HA to the panels for temp and AQI (I live in a wild fire area) and other information without having to deal with the instability of circuit python, which also last I looked had no OTA, so annoying.

**Comment by sekureco42** [comment]
Due the latest modifications on the component (also contributions from you) I will close this issue.
