### ISSUE TITLE
wifi updates fail

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [sekureco42/esphome-hub75#5]
I am trying to track this down - from time to time the wifi updates fail to start and the esp32 reboots. This happens more often on my 64x128 panels. My hunch is that I am taxing the esp32 to the end of its abilities, but any ideas on how I can tell this?

Have you ever seen a way to tell the external component to stop when an update is triggered? This might allow enough capacity to do the update.

Wifi works as normal else wise.

**Comment by sekureco42** [comment]
I had never issues with wireless updates. For those specific esphome related questions please ask on their discord.
